#!/bin/sh

# エラーや未定義変数への参照があれば即終了
set -eu

cd $HOME

DOTFILES_DIR=$HOME/dotfiles-linux
SHELL_DIR=$DOTFILES_DIR/sh
SYMLINK_DIR=$DOTFILES_DIR/symlink

# dotfilesをクローンする
if [ ! -d $DOTFILES_DIR ]
	then
		echo "公開鍵をGitHubに登録しましたか？[y/N]"
		read answer
		case $answer in
		[Yy]* )
			;;
		* )
			echo "公開鍵をGitHubに登録してからやり直してください。"
			echo "1. ssh-keygen -t ed25519 -C YOUR_EMAIL_ADDRESS"
			echo "2. pbcopy < ~/.ssh/id_rsa.pub"
			echo "詳細は https://docs.github.com/ja/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account を確認してください。"
			exit 0
			;;
		esac

		echo "dotfilesをダウンロードしています..."
		git clone git@github.com:ymgn9314/dotfiles_linux.git
	else
		echo "dotfilesは既にダウンロードされています。"
		echo "インストールを続行しますか？[y/N]"
		read answer
		case $answer in
		[Yy]* )
			;;
		* )
			echo "インストールを中止します。"
			exit 0
			;;
		esac
fi

sudo ln -sf $SYMLINK_DIR/.gitconfig $HOME/.gitconfig
sudo ln -sf $SYMLINK_DIR/.zshrc $HOME/.zshrc
sudo ln -sf $SYMLINK_DIR/.zsh/ $HOME/.zsh

sh $SHELL_DIR/setup_utils.sh
sh $SHELL_DIR/setup_cui.sh
sh $SHELL_DIR/setup_gui.sh
