# git
alias g="git"
alias gs="git status"
alias gd="git diff"
alias gdc="git diff --cached"
alias gpl="git pull"
alias gps="git push"
alias gc="git commit"
alias gcm="git commit -m"
alias ga="git add"